

spring:
  application:
    name: GoodInfluenceShop
  config:
    import: classpath:s3.yml
  datasource:
    url: jdbc:h2:mem:fixed_db  # 고정된 데이터베이스 이름 사용
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

external:
  jwt:
    tokenSecretKey: asdlkfjadlkfj123112k3j12kl3j1k2j3k1l23k1j2l3h12liaufha9f8w452398t7t23k423r0wd9ga98283723lkjskdfa0sd9ga7g7h6a
    tokenPrefix: Bearer/u0020
    accessKey: Authorization
    accessTokenExpirationTime: 43200000 #12시간
    refreshKey: RefreshToken
    refreshTokenExpirationTime: 604800000 #7일
