

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  application:
    name: GoodInfluenceShop
  config:
    import: classpath:s3.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://walab.handong.edu:3306/p3_21900613?useSSL=false
    username: p3_21900613
    password: a5hS7Fzm6MGoWBLH

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

external:
  jwt:
    tokenSecretKey: asdlkfjadlkfj123112k3j12kl3j1k2j3k1l23k1j2l3h12liaufha9f8w452398t7t23k423r0wd9ga98283723lkjskdfa0sd9ga7g7h6a
    tokenPrefix: Bearer/u0020
    accessKey: Authorization
    accessTokenExpirationTime: 43200000 #12시간
    refreshKey: RefreshToken
    refreshTokenExpirationTime: 604800000 #7일
